# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Quantitative Ecology
author: Lehman, Loberg and Clark
logo: img/logo.png

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: quantitative-ecology.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/MikheyevLab/ecology-textbook  # Online location of your book
  path_to_book: book  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true

launch_buttons:
  notebook_interface: "classic" # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url: "https://mybinder.org"
  colab_url: "https://colab.research.google.com"
  thebe: true
